theme = "monokai_pro"

[editor]
line-number = "relative"
mouse = true
cursorline = true
true-color = true
rulers = [80]
color-modes = true
completion-timeout = 15
bufferline = "multiple"
#end-of-line-diagnostics="warning"


[editor.statusline]
left = ["mode", "spinner", "file-name"]
#right = ["diagnostics", "workspace-diagnostics", "version-control", "selections", "position", "file-encoding", "file-type"]
right = ["diagnostics", "separator", "workspace-diagnostics", "selections", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = true
# Show LSP messages in the status line
display-messages = true
display-inlay-hints = true

[editor.smart-tab]
supersede-menu = true

#[editor.inline-diagnostics]
#cursor-line = "error"
#
#####################################
# Keys
[keys.insert]
"C-[" = "normal_mode"

[keys.normal]
# C-p = "@:sh "
- = "@zt k"
C-p = "@:lsp-workspace-command "

[keys.select]
"g" = { "e" = "goto_file_end" }
