theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
rulers = [120]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"C-[" = "normal_mode"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
