theme = "monokai_pro"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
rulers = [80]
color-modes = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"C-[" = "normal_mode"

[editor.indent-guides]
render = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = true
# Show LSP messages in the status line
display-messages = true
